// client/tat-ui/src/App.tsx
import { Route, BrowserRouter as Router, Routes } from 'react-router-dom';

import Header from './_component/Header/Header';
import Archive from './_pages/Archive';
import Contact from './_pages/Contact';
import Main from './_pages/Main';
import Reservation from './_pages/Reservation';

function App() {
	return (
		<div className='App'>
			<Router>
				<Header />
				<Routes>
					<Route path='/' element={<Main />} />
					<Route path='/archive' element={<Archive />} />
					<Route path='/contact' element={<Contact />} />
					<Route path='/reservation' element={<Reservation />} />
				</Routes>
			</Router>
		</div>
	);
}

export default App;

// client/tat-admin/src/App.svelte
<script lang="ts">
  import { Router, Route } from 'svelte-navigator';
  import Auth from './_pages/Auth.svelte';
  import Main from './_pages/Main.svelte';
  import Login from './_pages/Login.svelte';
</script>

<Router>
    <Route path="login">
      <Login/>
    </Route>
    <Route path="main">
      <Auth />
      <Main />
    </Route>
</Router>

<style>
</style>
